- hosts: "Flimnoria"
  gather_facts: yes
  become: true

  tasks:
    - name: fedora provision | add packages
      dnf:
        state: present
        name: "{{ item }}"
      with_items:
        - pipenv
        - git
        - vim
        - python3-pip
    - name: fedora provision | supybot
      pip:
        name: "{{ item }}"
        extra_args: --user
      with_items:
      - limnoria
      - sgmllib3k
      - requests
      - pytz
      - simplejson
      - python-fedora
      - arrow
      - packagedb-cli
      - pyyaml
      - fedmsg
      become_user: vagrant
    - name: fedora provision | clone Flim
      git:
        repo: 'https://github.com/XakV/Flimnoria.git'
        dest: /home/vagrant/Flimnoria
